Iter9
ShukinDmitriy/shortener pull request #10
Opened 2024-02-26 21:10 UTC by ShukinDmitriy

save data in file

2024-02-29 16:59 UTC, popoffvg requested changes

2024-02-29 16:59 UTC, popoffvg commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
В запе уже есть готовый синглтон. Он устанавливается zap.ReplaceGlobals

2024-02-29 16:59 UTC, popoffvg commented on internal/models/db.go
> +		directory := strings.Join(dirPaths[0:len(dirPaths)-1], "/")
Стоит воспользоваться пакетом path для конкатенации имени директорий

2024-02-29 16:59 UTC, popoffvg commented on internal/models/db.go
> +type Event struct {
Стоит разместить Event рядом с другими моделями

2024-02-29 16:59 UTC, popoffvg commented on internal/middleware/request-info.go
> +package middleware
В имени файла  `-` стоит заменить на `_`

2024-02-29 16:59 UTC, popoffvg commented on internal/middleware/request-info.go
> +		logger       zap.Logger
Логгер стоит хранить по указателю. Также можно использовать zap.SugarLogger с более удобным интерфейсом

2024-02-29 16:59 UTC, popoffvg commented on internal/middleware/request-info.go
> +		mutex        sync.RWMutex
Мьютекс следует хранить по указателю, т.к. при передаче стурктуры по RequestInfo по значению мьютекс перестанет работать

2024-02-29 16:59 UTC, popoffvg commented on internal/middleware/request-info.go
> +	RequestInfo struct {
Лучше не делать дополнительную абстракцию и обойтись мидлварами

2024-02-29 16:59 UTC, popoffvg commented on internal/middleware/request-info.go
> +		ri.mutex.Lock()
мьютекст тут не нужен. Добавив мьютекст твой сервис стал однопоточным, что катастрофически скажется на производтельности

2024-02-29 17:00 UTC, popoffvg commented on internal/models/db.go
> +func NewProducer(filename string) (*Producer, error) {
Работа с файлами должна быть в отдельном пакете

2024-02-29 17:01 UTC, popoffvg commented on cmd/shortener/main.go
> +		event, err = models.DBConsumer.ReadEvent()
При получении URL не стоит искать в файле, а обойтись поиском в мапе, которая при старте сервиса быть синхронизирована с файлам и потом обновляться вместе с записью в файл

2024-03-03 17:38 UTC, ShukinDmitriy commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Удалил переменную, поменял на использование zap.L()

2024-03-03 17:45 UTC, ShukinDmitriy commented on internal/models/db.go
> +		directory := strings.Join(dirPaths[0:len(dirPaths)-1], "/")
поменял

2024-03-03 17:46 UTC, ShukinDmitriy commented on internal/models/db.go
> +type Event struct {
перенес

2024-03-03 17:47 UTC, ShukinDmitriy commented on internal/middleware/request-info.go
> +package middleware
переименовал файлы

2024-03-03 17:50 UTC, ShukinDmitriy commented on internal/middleware/request-info.go
> +		ri.mutex.Lock()
удалил использование мьютекса

2024-03-03 18:01 UTC, ShukinDmitriy commented on internal/middleware/request-info.go
> +		logger       zap.Logger
учту в будущем, сейчас переделал реализацию в соответствии с замечаниями

2024-03-03 18:01 UTC, ShukinDmitriy commented on internal/middleware/request-info.go
> +		mutex        sync.RWMutex
учту в будущем, сейчас переделал реализацию в соответствии с замечаниями

2024-03-03 18:01 UTC, ShukinDmitriy commented on internal/middleware/request-info.go
> +	RequestInfo struct {
переделал на функции

2024-03-03 18:18 UTC, ShukinDmitriy commented on cmd/shortener/main.go
> +		event, err = models.DBConsumer.ReadEvent()
переделал

2024-03-03 18:19 UTC, ShukinDmitriy commented on internal/models/db.go
> +func NewProducer(filename string) (*Producer, error) {
Замечание не понятно, т.к. в этом файле по сути только и есть работа с файлом.

2024-03-05 06:07 UTC, merged