Iter15 Удаление URL
ShukinDmitriy/shortener pull request #16
Opened 2024-03-29 23:17 UTC by ShukinDmitriy

2024-04-01 07:48 UTC, popoffvg requested changes

2024-04-01 07:48 UTC, popoffvg commented on cmd/shortener/shortener.go
> +		events = append(events, event)
Нет буферизации. Удаляешь по одному событию, т.к. код в `deleteEvents` выполняется синхронно в одни поток.

2024-04-01 07:48 UTC, popoffvg commented on cmd/shortener/shortener.go
> +func (us *URLShortener) deleteEvents() {
При завершении работы сервера теряешь данные, т.к. не все события могут быть удалены. Необходимо учесть завершение работы сервера через gracefull shutdown и не завершать работу пока весь буфер не будет отправлен на диск.

2024-04-01 07:48 UTC, popoffvg commented on cmd/shortener/shortener.go
> +	events := us.URLRepository.GetEventsByUserID(ctx.Request().Context(), userID)
В твоей реализации этот метод будет работать, т.к. сброс на диск синхронный почти. Если сделаешь асинхронный нужно учитывать буфер событий

2024-04-03 18:45 UTC, ShukinDmitriy commented on cmd/shortener/shortener.go
> +	events := us.URLRepository.GetEventsByUserID(ctx.Request().Context(), userID)
не совсем понял замечание. создание записей синхронное. и по заданию его не требовалось делать асинхронным.
если же рассматривать теоретическую возможность такой реализации, то я бы привел пример поисковых индексов, когда есть временной лаг между фактическим изменением данных и тем как мы видим эти изменения в интерфейсе. т.е. я хочу сказать, что проще принять риск лага вместо того чтобы городить запрос у условную бд и временное хранилище данных.

2024-04-03 20:26 UTC, ShukinDmitriy commented on cmd/shortener/shortener.go
> +func (us *URLShortener) deleteEvents() {
Добавил сохранение на диск и ожидание этого процесса

2024-04-03 20:27 UTC, ShukinDmitriy commented on cmd/shortener/shortener.go
> +		events = append(events, event)
переписал это место, добавил логику ожидания команды на завершение

2024-06-27 20:55 UTC, merged